#!/usr/bin/env bash
# =============================================================================
# program.sh — Program the Arrow MAX1000 FPGA over USB using openFPGALoader.
#
# Requirements (host Mac):
#   brew install openfpgaloader
#
# What it does:
#   1. Checks openFPGALoader is installed.
#   2. Looks for a connected MAX1000 / Arrow USB-Blaster.
#   3. Programs quartus_output/quartus-output-<branch>-<name>/cpu_fpga.pof into internal flash
#      (permanent — bitstream survives power-cycles).
#
# Usage:
#   ./program.sh <name>   — program flash  (e.g. ./program.sh fibonacci)
# =============================================================================

#set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRANCH=$(git rev-parse --abbrev-ref HEAD)
# Sanitize branch name to match the artifact-naming convention used by
# build_and_download.sh and the synthesize.yml workflow.
BRANCH_SAFE="${BRANCH//[\/:\*\?\"\<\>\|\\]/-}"

# Colour helpers
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${BOLD}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Parse arguments: <name>
# ---------------------------------------------------------------------------
NAME=""

for arg in "$@"; do
    NAME="${arg%.asm}"   # strip .asm suffix if included
done

[[ -n "$NAME" ]] || die "Usage: $0 <name>\n  e.g. $0 fibonacci"

OUTPUT_DIR="${SCRIPT_DIR}/quartus_output/quartus-output-${BRANCH_SAFE}-${NAME}"
POF_FILE="${OUTPUT_DIR}/cpu_fpga.pof"

# ---------------------------------------------------------------------------
# 1. Check openFPGALoader is installed
# ---------------------------------------------------------------------------
if ! command -v openFPGALoader &>/dev/null; then
    die "openFPGALoader not found.\n\nInstall it with:\n  brew install openfpgaloader\n\nThen re-run this script."
fi

OFPL_VERSION=$(openFPGALoader --Version 2>&1 | head -1)
info "openFPGALoader: ${OFPL_VERSION}"
info "Program: ${NAME}  (${OUTPUT_DIR}/)"

# ---------------------------------------------------------------------------
# 2. Detect the MAX1000 / Arrow USB-Blaster
#    The Arrow MAX1000 uses an FTDI FT2232H as its USB-Blaster.
#    It is not in openFPGALoader's board list, so we always use --cable ft2232.
# ---------------------------------------------------------------------------
CABLE_FLAG="--cable ft2232"

info "Scanning for JTAG devices ..."
if openFPGALoader ${CABLE_FLAG} --detect 2>&1 | grep -qi "10M16S"; then
    ok "Arrow MAX1000 (10M16SAU169C8G) detected."
else
    warn "Could not confirm MAX1000 on JTAG chain — attempting to program anyway ..."
fi

# ---------------------------------------------------------------------------
# 3. Program the device (internal flash — permanent)
# ---------------------------------------------------------------------------
[[ -f "${POF_FILE}" ]] \
    || die "POF file not found: ${POF_FILE}\nRun ./build_and_download.sh ${NAME} first."

info "Programming internal flash with: ${POF_FILE}"
warn "Flash programming takes ~30 s. Do not disconnect the board."

openFPGALoader ${CABLE_FLAG} --write-flash "${POF_FILE}"
ok "Flash programming complete. Bitstream will survive power-cycles."

# ---------------------------------------------------------------------------
# Notes on permanent flash programming
# ---------------------------------------------------------------------------
# MAX 10 has internal flash.  The POF file is generated by Quartus via
# File → Convert Programming Files (target: CFM / Configuration Flash Memory).
# ---------------------------------------------------------------------------
